/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_gvsmirnov_perv_labs_rekt_ChecksumCalculator */

#ifndef _Included_ru_gvsmirnov_perv_labs_rekt_ChecksumCalculator
#define _Included_ru_gvsmirnov_perv_labs_rekt_ChecksumCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_gvsmirnov_perv_labs_rekt_ChecksumCalculator
 * Method:    calculateChecksum
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ru_gvsmirnov_perv_labs_rekt_ChecksumCalculator_calculateChecksum
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
